### ISSUE TITLE
'+' characters are removed from tags when saving a page

### ISSUE THREAD

**Issue by davidag** [Cito/Pinboard-Pin#17] opened 2019-09-18 11:45 UTC
When saving a page (new or existing), plus (+) characters are removed from tags. I've come across this problem because I usually save `c++` tagged pages, which end up being `c` tagged.

This doesn't happen with minus (-), asterisk (*) or slash (/) characters, for example.

Tested with Firefox 69.0.

**Comment by Cito** [comment] 2019-09-25 16:53
Thanks for reporting this issue, @davidag. I could reproduce it and found that it is caused by a [bug in Angular](https://github.com/angular/angular/issues/18261) for which I will need to add a workaround.

**Comment by Cito** [comment] 2019-09-25 17:38
Should be fixed now in v0.2.8.

**Closed by Cito** 2019-09-25 17:38 UTC

**Comment by davidag** [comment] 2019-09-25 19:59
Thank you @Cito! Great work!
