### ISSUE TITLE
hangs on "loading page from pinboard"

### ISSUE THREAD

**Issue by tweitzel** [Cito/Pinboard-Pin#1] opened 2017-03-23 18:35 UTC
Sometime this week, the extension has stopped working. When I click the pin button, I get the popup but all the options are disabled while the title of the box reads "loading page from pinboard." I turned on live http headers but it doesn't seem to be producing any network activity at all.

**Comment by Cito** [comment] 2017-03-24 12:02
Seems it has been fixed now.

**Closed by Cito** 2017-03-24 12:02 UTC

**Comment by davidag** [comment] 2020-01-15 09:31
This seems to be happening again for some days now. I'm unable to use the extension at all. If there's any other information I can provide you @Cito just let me know. Thank you so much!

**Comment by Cito** [comment] 2020-01-15 09:58
This has been reported in #21 as well, but it seems to be caused by the API. Just now tried it myself, was able to add and delete a bookmark, but it was unusual slow. So it looks like the add-on still works, but the API is sometimes slow or unreliable. Unfortunately there is nothing I can do about the API service, you will need to contact the Pinboard support.

**Comment by davidag** [comment] 2020-01-20 15:39
@Cito Thank you for your response! It's working normally now. Next time I'll get in touch with Pinboard support. Sorry for the inconvenience.
